const products = [
  {
    idProduct: 34,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUIAPRACTICAFISICAII2DAEDICIN_yyFihf17WDBlsO1UJDgn_38513026-0ac5-47d7-991e-ae8c705114f4.jpg',
    nombre: 'Fisica II',
    descripcionCorta: 'Guía de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'IND16-0317,CIV14-0320',
  },
  {
    idProduct: 35,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUIADEPRCTICADEESTADSTICA_dVjSJUhdqjQTAlZxqRIi_1d4df9e1-c10b-41dd-af16-bd173a44c2ca.jpg',
    nombre: 'Estadística y Probabilidades',
    descripcionCorta: 'Guía de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'AD11-0430,MA203,CIV14-0427,CO11-0527',
  },
  {
    idProduct: 36,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUIADEPROBLEMASDEQUMICAI_84D6o5NqRZ8vnWlfu7HB_295c98dd-7358-40b0-a858-d1518e674bad.jpg',
    nombre: 'Química I',
    descripcionCorta: 'Guía de Problemas',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'AMB20-0106,IND16-0102,',
  },
  {
    idProduct: 37,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUADEPRCTICADEFISICAI_8QOtumyvk31wlFFFzpI2_1630d763-21a9-44cd-894f-67cb0a63d3c4.jpg',
    nombre: 'Fisica I',
    descripcionCorta: 'Guía de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'IND16-0209,CIV14-0211',
  },
  {
    idProduct: 38,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUAPRCTICADEDIBUJOTCNICO_LmDhQEGOJbfj6Fs7Qyw1_6279e892-53a7-4591-8359-9fe943724d05.jpg',
    nombre: 'Dibujo Técnico y CAD',
    descripcionCorta: 'Guía de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'CIV14-0210',
  },
  {
    idProduct: 39,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/CLCULOENUNAVARIABLE_5z1sHGosXWlNMSGPz7eG_4b358566-2b97-45ce-8eba-e38f32f3a11c.jpg',
    nombre: 'Cálculo en una Variable',
    descripcionCorta: 'Guía de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'MA102,CIV14-0209,MAT203I,IND16-0208',
  },
  {
    idProduct: 40,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUIADEALGEBRAYGEOMETRIAPARAADMINISTRACION_1ed6ZY1HREfyk6FNvCq1_8279ee97-77d6-4d7e-b317-7f245e8ab03f.jpg',
    nombre: 'Álgebra y Geometría',
    descripcionCorta: 'Guía de Práctica. CC.EE',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'AD11-0211',
  },
  {
    idProduct: 41,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUADEPRCTICADEALGEBRAYGEOMETRAFACULTADDEINGENIERAS_RgBKJKCXrOFvLHxFPNSR_511ac4d7-c2d4-4694-b5a1-afc0b21bc36e.jpg',
    nombre: 'Álgebra y Geometría',
    descripcionCorta: 'Guía de Práctica. Ingenierías',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: 'IND16-0207,CIV14-112,MAT102I',
  },
  {
    idProduct: 42,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 0.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/GUIADEFUNDAMENTOSDECONTABILIDAD_CSgWSIDHFWYvzvQT2aVT_eac73842-921a-4755-b313-e2fb052cfbc0.jpg',
    nombre: ' GUÍA DE PRÁCTICA DE FUNDAMENTOS DE CONTABILIDAD',
    descripcionCorta: 'Guías de Práctica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: true,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 43,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 100.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AURELIODAZESPINOZALEGADOMUSICAL_FQfA0HD2fqU3IoE9qa9P_3bc8c781-3072-4393-9caa-0d2e0a239631.jpg',
    nombre: 'AURELIO DÍAZ ESPINOZA. LEGADO MUSICAL',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 44,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 80.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/OBRAPERIODSTICA_Wycq4abVHAPpo7ZWIitV_518ffa6a-b87f-4f83-8056-5e8f418272f9.png',
    nombre: 'OBRA PERIODÍSTICA (TAPA DURA)',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 45,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 65.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/OBRAPERIODSTICA_8uYNK33q8QbSedmNSLEz_e782a463-a4dc-45b4-97a3-487a6abe7a0b.png',
    nombre: 'OBRA PERIODÍSTICA (TAPA RÚSTICA)',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 46,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 90.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AYAVIRI_1Llmt2p0mrGNV5gxVV1j_78b55871-4a96-459a-9ec6-6bbcc151f729.jpg',
    nombre: ' AYAVIRI',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 47,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 70.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LOSDUNCKERS_GGwifiNrx8ownP9Qq2wI_5e1a034c-1f51-4d3a-ad6f-6359f891f816.png',
    nombre: 'LOS DUNCKER VIDA Y OBRA',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 48,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 50.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/INVOCANDOALINFINITO_aypOl4hNZuiulZRWtYj1_678d266a-f280-4ee6-ba0d-f746721c238c.jpg',
    nombre: 'INVOCANDO AL INFINITO',
    descripcionCorta: 'Arte e Investigación ',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 49,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 130.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/MSICAENLACATEDRALDEAREQUIPA_5ROQXKOxNEosKc2Hd4Xm_24d1567f-a9dc-46ba-a4bd-781b0c2c90d5.jpg',
    nombre: 'MÚSICA EN LA CATEDRAL DE AREQUIPA 1609-1881',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 50,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 95.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/OPERACIONAYAR_53Xs6vdsvIjudE98rFKt_1ecdb8e3-4a5e-4367-9b7e-5c1cb6108d9d.jpg',
    nombre: 'OPERACIÓN ÁYAR',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 51,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 65.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/MIAMORLAMSICA_MTE94emZXSnTIZB2NY9c_fefbff9d-3c08-476d-ac3a-ffb39564968b.jpg',
    nombre: 'MI AMOR, LA MÚSICA',
    descripcionCorta: 'Arte e Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 52,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 95.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/MORALECONMICA_X87V0LMe9EnfaULVh5js_2e29a5b0-e174-4f55-be3b-a3ef049ca1e9.jpg',
    nombre: 'MORAL ECONÓMICA',
    descripcionCorta: 'Responsabilidad Social de la Empresa',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 53,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ASPECTOSINNOVADORESDELAEMPRESA_THK2QPIC3s1m6pxWKtf0_1bfcb041-17ff-4d89-bbbd-8a9db3c00d06.jpg',
    nombre: 'ASPECTOS INNOVADORES DE LA EMPRESA EN LA CENTESIMUS ANNUS',
    descripcionCorta: 'Responsabilidad Social de la Empresa',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 54,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 55.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/MUNDOSANMALOS_KFkiudTUnsgLGXVRgIGn_1cf5cd80-7fa3-42d1-8139-536ae82c95c5.jpg',
    nombre: 'MUNDOS ANÓMALOS. UN ENSAYO DE FENOMENOLOGÍA PSIQUIÁTRICA',
    descripcionCorta: 'Biblioteca de Psicología',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 55,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 40.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/CRITERIOSDESALUDPSICOLOGICA_gNusRyE8ZWnUl0bsBzPd_9b6e4c15-4d93-4b1a-b4b6-a03e413f4e56.jpg',
    nombre:
      'CRITERIOS DE SALUD PSICOLÓGICA SEGÚN ALBERT ELLIS Y LAS ENSEÑANZAS DE LA TRADICIÓN CRISTIANA SOBRE L',
    descripcionCorta: 'Biblioteca de Psicología',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 56,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 40.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/RUDOLFALLERS_8KeNbEoRZDvS46J9CwPl_0dc55492-296a-45b5-bc1f-eb5e402a6643.jpg',
    nombre:
      'RUDOLF ALLERS. PSIQUIATRA DE LO HUMANO. PARA UNA PSICOLOGÍA FILOSÓFICO – ANTROPOLÓGICA DE LA PERSONA',
    descripcionCorta: 'Biblioteca de Psicología',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 57,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 53.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/EDUCACINDELAVIRTUD_pw2jyKPsZ9Q3gpt0sQRJ_76584f6d-b258-456d-ab99-62c051710923.jpg',
    nombre: 'EDUCACIÓN DE LA VIRTUD EN LOS ÁMBITOS FAMILIAR Y ESCOLAR',
    descripcionCorta: 'Educación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 58,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/BASESROMANISTASDELDERECHO_lYkIebgV2gUNdBn54WlG_a6ff5a32-7d5e-48ed-87fc-573a9c912589.jpg',
    nombre: 'BASES ROMANISTAS DEL DERECHO CONTEMPORÁNEO',
    descripcionCorta: 'Derecho',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 60,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 60.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LECCIONESDEDERECHOINTERNACIONALPBLICO_JCCIfmMXiQtXnNXtcO6L_5bf2bb13-1373-470c-8ef4-40acb61e6add.jpg',
    nombre: 'LECCIONES DE DERECHO INTERNACIONAL PÚBLICO',
    descripcionCorta: 'Derecho',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 61,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 53.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LAPERSONACOMOSERENRELACIN_ipF58xARsdMtpd5AQX66_d8679133-88ad-4ab7-a75b-9e45809e8b01.jpg',
    nombre:
      'LA PERSONA COMO SER EN RELACIÓN EN EL PENSAMIENTO DE JULIÁN MARÍAS',
    descripcionCorta: 'Teología, Filosofía y Vida Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 63,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/NATURALEZADELACOMUNIN_tTE3u0ZchRWqXK4IP9NX_c6bed533-ebe6-454b-bbcb-d082e2ccfbe8.jpg',
    nombre: ' NATURALEZA DE LA COMUNIÓN. ENSAYO SOBRE LA RELACIÓN',
    descripcionCorta: 'Filosofía, Teología y Vida Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 64,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/SANAGUSTNYLARECONCILICIN_dPNwj4wgS76mBd7hIMp4_79527f1c-2433-4060-8be4-9d916196fbd1.jpg',
    nombre: 'SAN AGUSTÍN Y LA RECONCILIACIÓN',
    descripcionCorta: 'Teología, Filosofía y Vida Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 65,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 28.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ELCARDENALVANTHUAN_AwxgA4vM0zkoEC3TGMs5_46b2d7ee-d923-4a36-9f94-6503c607fdb3.jpg',
    nombre: ' EL CARDENAL VAN THUÂN. LA FUERZA DE LA ESPERANZA',
    descripcionCorta: 'Teología, Filosofía y Vida Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 69,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 40.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ELMISTERIODELAPERSONA_zk0EM9VDFEggCReHpwvd_1d387e58-abd9-48df-aefc-bcaf9526272d.jpg',
    nombre:
      'EL MISTERIO DE LA PERSONA. REFLEXIONES ANTROPOLÓGICAS EN LA SENDA DEL CONCILIO VATICANO',
    descripcionCorta: 'Teología, Filosofía y Visa Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 70,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 85.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LAFAMILIACLAVEDELDIALOGO_PX0wqfdvMwxbxJpnpNhk_8ed81679-6b67-4ccb-a0e4-24d64bc1e773.jpg',
    nombre:
      'LA FAMILIA: CLAVE DEL DIALOGO IGLESIA-MUNDO EN EL 50° ANIVERSARIO DE LA GAUDIUM ET SPES',
    descripcionCorta: 'Familia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 71,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 30.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/TIPOSDEFAMILIA_Xc70zhWwdkWbWW8lVvrH_853090a5-7934-4943-9e12-01f27627b527.jpg',
    nombre: ' TIPOS DE FAMILIA Y BIENESTAR DE NIÑOS Y ADULTOS',
    descripcionCorta: 'Familia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 72,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 58.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/FAMILIAYDESARROLLOSOSTENIBLE_6QySr7c6JayNCO0neIdC_1509e5e8-afe7-46f9-a7d1-41edceb04964.png',
    nombre: 'FAMILIA Y DESARROLLO SOSTENIBLE',
    descripcionCorta: 'Familia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 73,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 30.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/VIDASEXUALENELMATRIMONIO_bhnxHiESmqoCzadXw9cP_1dbf5417-d9c5-4823-ae00-64e37bcf7328.png',
    nombre: 'VIDA SEXUAL EN EL MATRIMONIO',
    descripcionCorta: 'Familia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 74,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 25.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/QUEESLAVIDA_o07yGIAoSR2lr2IqkewM_646e8d4c-e050-4155-bf83-6ef6c294d9a1.jpg',
    nombre: ' ¿QUÉ ES LA VIDA? LA BIOÉTICA A DEBATE',
    descripcionCorta: 'Familia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 75,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/EXCORDEECCLESIAE_C1iPrSGGxh8s1A9H9agP_f2468b54-d572-477c-8296-af024d5d3101.jpg',
    nombre:
      'CONSTITUCIÓN APOSTÓLICA. EX CORDE ECLESSIAE DEL SUMO PONTIFICE JUAN PABLO II.',
    descripcionCorta: 'Clasicos Cristianos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 76,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 55.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/SENTENCIASTOMOI_lCElIVyjHziLmiMyBvFZ_7b037d82-0e40-414d-886e-f3b7c08e185e.png',
    nombre: ' SENTENCIAS. TOMO I',
    descripcionCorta: 'Clásicos Cristianos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 77,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 55.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/SENTENCIASTOMOII_MYwU5CIRmwVEEkIdFEV1_50bbc32f-b077-4e8a-98a7-1901f3f9ecbf.png',
    nombre: 'SENTENCIAS. TOMO II',
    descripcionCorta: 'Clásicos Cristianos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 92,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LAIGLESIAYLAEDUCACINENELPER_TtRPVKZkWzjx7lbadbVm_4d94f815-567f-484d-a08b-41effb6be642.jpg',
    nombre: ' LA IGLESIA Y LA EDUCACIÓN EN EL PERÚ',
    descripcionCorta: 'Cultura Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 93,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 7.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/HACIAUNACULTURADELAVERDAD_M1kZdCbVwRS8necziTtG_4031a986-2abd-4ab0-8d1a-1a4b4511ecc5.jpg',
    nombre: 'HACIA UNA CULTURA DE LA VERDAD',
    descripcionCorta: 'Cultura Cristiana',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 94,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 30.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/DERECHOYMORAL_2XPVVJglm7VPyIjh0PsH_85cd01c1-4134-4d73-bc3d-b68ea39688d6.jpg',
    nombre: 'DERECHO Y MORAL EN EL DEBATE IUSFILOSÓFICO CONTEMPORÁNEO',
    descripcionCorta: 'Eventos Académicos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 95,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 27.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/PSICOLOGAYVISINDELHOMBREDESDELAFE_LX967uFbpUCkH1CqAShV_ffd89f43-66b9-47d8-9a76-5f8c6303c8ca.jpg',
    nombre: 'PSICOLOGÍA Y VISIÓN DEL HOMBRE DESDE LA FE',
    descripcionCorta: 'Eventos Académicos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 96,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/RELACIONESENTRELAIGLESIAYELESTADOPERUANO_v2tkpJj8USYyOj2ApDCz_816f16e9-f67f-43b7-95dc-d89cdf137335.jpg',
    nombre: 'RELACIONES ENTRE LA IGLESIA CATÓLICA Y EL ESTADO PERUANO',
    descripcionCorta: 'Eventos Académicos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 97,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 8.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/IGLESIAYCULTURAENAMERICALATINA_IvmAFOdX39u2YzIb8jSu_65a7a361-6ed3-4532-8819-b03685b09206.jpg',
    nombre: 'IGLESIA Y CULTURA EN AMÉRICA LATINA',
    descripcionCorta: 'Eventos Académicos',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 98,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LACOMUNICACINPOLTICA_KiSOWxAGA0ThArod9EGY_14d578e6-8f50-4a15-bf75-dbc7fb29e2e5.jpg',
    nombre:
      'LA COMUNICACIÓN POLÍTICA EN LOS GOBIERNOS LATINOAMERICANOS 2010-2014',
    descripcionCorta: 'Reflexión Contemporánea',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 99,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/IDENTIDADCULTURAYDESARROLLOENAMRICALATINA_aUnsyB3VyMnyEA1hPiYJ_3723cd40-ae28-4388-b530-c18e282490cf.JPG',
    nombre: 'IDENTIDAD, CULTURA Y DESARROLLO EN AMÉRICA LATINA',
    descripcionCorta: 'Reflexión Contemporánea',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 100,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/REFORMASECONMICASYPRIVILEGIOS_fTHrKnqfsYlbvwRnA5pH_6036042b-2e24-4ede-941e-5f0101dd49ac.jpg',
    nombre: 'REFORMAS ECONÓMICAS Y PRIVILEGIOS COMERCIALES',
    descripcionCorta: 'Historia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 101,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 60.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/HISPANOAMRICA_FQgXl1hqAPRhI04jZxsg_c6f6dcde-24df-414d-bb85-ac2fcd747b94.jpg',
    nombre: 'HISPANOAMÉRICA',
    descripcionCorta: 'Historia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 117,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 25.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LALUZHABITAENLOSTRIGALES_uNLm1g4SrFJglfJsIvcp_e26f4dc9-ea4f-4280-a4ad-5209dd6fe749.jpg',
    nombre: 'LA LUZ HABITA EN LOS TRIGALES',
    descripcionCorta: 'Poemarios',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 118,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AZULDEMARADENTRO_IJbmPCZXy7uDijqBoJOV_854431e5-a7f8-4808-80ca-39870bae1a13.jpg',
    nombre: 'AZUL DE MAR ADENTRO',
    descripcionCorta: 'Poemarios',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 119,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/REVISTAPERSONAYCUTLURA16_MRVO2zexvlTKdqGDR43x_42443756-dc61-4146-97fd-9f0f6ec7133a.jpg',
    nombre: 'REVISTA PERSONA Y CULTURA AÑO 16, N.16',
    descripcionCorta: 'Revista Persona y Cultura',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 120,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/REVISTAPERSONAYCULTURA15_6di53jvKFz7lF1Lg0Wr3_5fc8ac12-e50e-4b4a-9bd1-27ddf85ee1d3.jpg',
    nombre: 'REVISTA PERSONA Y CULTURA AÑO 15, N.15',
    descripcionCorta: 'Revista Persona y Cultura',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 121,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/REVISTAPERSONAYCULTURA14_gpq8eIkK1quh6vkdrJ9t_c8cb93bb-f3f7-423b-b3cb-eec60ee87564.jpg',
    nombre: ' REVISTA PERSONA Y CULTURA AÑO 14, N.14',
    descripcionCorta: 'Revista Persona y Cultura',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 122,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 45.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/REVISTAPERSONAYCULTURA13_ZLr8G9WKEPzFUXYjb0wQ_bdc10e4f-7f10-43dc-b5a2-7ef168291a77.jpg',
    nombre: 'REVISTA PERSONA Y CULTURA AÑO 13, N.13',
    descripcionCorta: 'Revista Persona y Cultura',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 123,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 30.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/APUNTESSOBREDSI_3zCtikRRd8MdCi02dIV8_ca8ba5d3-e266-453f-ab4e-80a441c47db6.jpg',
    nombre: 'APUNTES SOBRE LA DSI',
    descripcionCorta: 'Doctrina Social de la Iglesia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 124,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/QUINTOINFORMEDELADSI_7lDOeBuPZ0aUgLQQRdpq_1f1c49a5-edce-4e22-ad2c-02f21dc15c05.jpg',
    nombre:
      'CRISIS JURÍDICA O INJUSTICIA. QUINTO INFORME SOBRE LA DOCTRINA SOCIAL CATÓLICA EN EL MUNDO',
    descripcionCorta: 'Doctrina Social de la Iglesia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 125,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/CUARTOINFORMEDELADSI_5uuXhVFumFjfGZJ9H3Wj_9c555f52-6698-45f9-99fd-250c61bc5c44.jpg',
    nombre:
      'IDEOLOGÍA DE GÉNERO Y NATURALEZA HUMANA. CUARTO INFORME SOBRE LA DOCTRINA SOCIAL CATÓLICA EN EL MUND',
    descripcionCorta: 'Doctrina Social de la Iglesia',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 126,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ESTABILIDADLABORALREFORZADA_4nZypjDFTRpQ6EhMFy54_f8bd601f-d079-400b-a7fb-3094c13c3ebd.jpg',
    nombre:
      'ESTABILIDAD LABORAL REFORZADA. LA MATERNIDAD Y LA DISCAPACIDAD ANTE EL DERECHO',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 127,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 48.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ELPRINCIPIOPROHOMINE_uBwG8Nn41CrtXvxzV1BO_25b0541a-903f-4554-b935-25b22d05351c.jpg',
    nombre:
      'EL PRINCIPIO PRO HOMINE COMO CLAVE HERMENÉUTICA DE LA INTERPRETACIÓN DE CONFORMIDAD. EL DIÁLOGO ENTR',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 128,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 48.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LAVULNERACIONDELAPERSONA_LuF8y2IOG9FSjf5he0gj_353d0cd3-d0c2-498c-bb6c-73b9f699ac42.jpg',
    nombre:
      'LA VULNERACIÓN DE LA PERSONA Y EL PRINCIPIO DE CULPABILIDAD EN LA TEORÍA DEL DERECHO PENAL DEL ENEMI',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 129,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ORIENTACINSEXUALYDISCRIMINACIN_fTcdAgXQ4skwbBS4GutM_a3946393-10f1-45b3-8d5a-e23c391d34c7.jpg',
    nombre:
      'ORIENTACIÓN SEXUAL Y DISCRIMINACIÓN EN EL SISTEMA INTERAMERICANO DE DERECHOS HUMANOS. UNA VALORACIÓN',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 130,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/DERECHOALAIDENTIDAD_bQfD3u1n64IERmQjLYYO_e334d8f9-14b9-4e3c-b640-6b6322b0e219.png',
    nombre: 'DERECHO A LA IDENTIDAD Y REPRODUCCIÓN HUMANA ASISTIDA HETERÓLOGA',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 131,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 35.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/LARELACINENTRELAPERSONAHUMANAYELDERECHO_XsPtzodajXqjpsfaMPpK_f0bfc635-cbdd-4edf-9cdd-7c6374ed3a19.jpg',
    nombre:
      'LA RELACIÓN ENTRE LA PERSONA Y EL DERECHO EN LA IUSFILOSOFÍA DE CARLOS FERNÁNDEZ SESSAREGO',
    descripcionCorta: 'Biblioteca Jurídica',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 132,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/CONDUCTASDISRUPTIVASYAUTOESTIMA_VdvWcP9mBGNiIAn5K8b2_303e5dd1-72d7-4a79-b755-7a02e57185c6.jpg',
    nombre:
      'CONDUCTAS DISRUPTIVAS Y AUTOESTIMA EN ESCUELAS MIXTAS Y DIFERENCIADAS EN AREQUIPA',
    descripcionCorta: 'Cuadernos de Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 133,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/IMPARCIALIDADEINDEPENDENCIAJUDICIAL_hCv0CaEUO0nLSnddNo8Q_496733fc-e65c-4674-a434-d37da19ba12f.jpg',
    nombre: 'IMPARCIALIDAD E INDEPENDENCIA JUDICIAL',
    descripcionCorta: 'Cuadernos de Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 135,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/ESTRESCRNICOENELTRABAJO_mPp4ej0AgPJXHFxipLuW_d7687e29-4615-4c53-a253-6ebedd9a3bd6.jpg',
    nombre:
      'ESTRÉS CRÓNICO EN EL TRABAJO: ESTUDIOS DEL SÍNDROME DE BURNOUT EN AREQUIPA',
    descripcionCorta: 'Cuadernos de Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 136,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 20.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/CRITERIOSPARALAASIGNACINDELGASTOSOCIAL_QdNQ2CCea7oFJbTN0nax_ce5c5fbf-b3b5-46e3-9359-e4a0170236e9.jpg',
    nombre:
      'CRITERIOS PARA LA ASIGNACIÓN DEL GASTO SOCIAL EN PROGRAMAS DE SALUD Y NUTRICIÓN EN EL PERÚ',
    descripcionCorta: 'Cuadernos de Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 137,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/DESAFIOSYTENSIONESDELADESCENTRALIZACIN_UYYEpT2WZa7uf5p6o4Vm_ae40d42d-4764-413e-a8f8-c4ecdc3213f6.jpg',
    nombre:
      'DESAFÍOS Y TENSIONES DE LA DESCENTRALIZACIÓN DE LA EDUCACIÓN EN EL PERÚ: UN ESTUDIO EN DIRECTORES DE',
    descripcionCorta: 'Cuaderno de Investigación',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 152,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 200.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/Defensadelacompetenciaypropiedadintelectual_tThbSeaFHJJevCwxDnJc_492224e4-d702-4211-98a0-caeacfe56abe.jpg',
    nombre:
      'Matricula de Diplomado en Defensa de la Competencia y Propiedad Intelectual',
    descripcionCorta:
      'Diplomado de postgrado destinado a la actualización y capacitación profesional en temas sobre eliminación de barreras burocráticas, derecho de la competencia y protección al consumidor, derecho de la propiedad intelectual.',
    descripcionExtendida: null,
    catDescripcion: 'DIPLOMADO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1005,
    idCatego: 6,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 153,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 3035.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/Defensadelacompetenciaypropiedadintelectual_bbo6pBIBhR2vSlgIchLQ_0596909c-8d66-4f8f-ba16-911f504ab590.jpg',
    nombre: 'Diplomado en Defensa de la Competencia y Propiedad Intelectual',
    descripcionCorta:
      'Diplomado de postgrado destinado a la actualización y capacitación profesional en temas sobre eliminación de barreras burocráticas, derecho de la competencia y protección al consumidor, derecho de la propiedad intelectual.',
    descripcionExtendida: null,
    catDescripcion: 'DIPLOMADO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1005,
    idCatego: 6,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 154,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 150.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/antropologiacristiana_6E5gZNPHnpsGcg1Zkhno_8aa920fe-f6c4-4785-9454-6de9479088aa.jpg',
    nombre: 'Matrícula Diplomado en Antropología Cristiana',
    descripcionCorta:
      'La matrícula es el primer paso para tu inscripción en cuotas. Con tu usuario accederás a tu cronograma de pagos.',
    descripcionExtendida: null,
    catDescripcion: 'DIPLOMADO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1005,
    idCatego: 6,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 155,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2850.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/antropologiacristiana_8sLTPEVLcULzKeEWtFKz_872d8803-c6ef-483a-941f-e328fa656a93.jpg',
    nombre: 'Diplomado en Antropología Cristiana',
    descripcionCorta:
      'El pronto pago hasta el 31 de julio y realiza un único pago que incluye la matrícula.',
    descripcionExtendida: null,
    catDescripcion: 'DIPLOMADO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1005,
    idCatego: 6,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 159,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos03_nMNJqcMbKULbd5NNvCnC_1bf7084d-2310-4ee8-b27f-0fed96ce35c1.jpg',
    nombre: 'PED EN FINANZAS ',
    descripcionCorta:
      'Domina las técnicas eficaces para gestionar los recursos financieros de tu empresa, tomando decisiones gerenciales acertadas en el área financiera. Realiza análisis financieros proponiendo diferentes soluciones.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 160,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos03_zwnCVqoofvPm0hJXT46w_510f07ae-9d11-4200-86e0-0efaa2268d87.jpg',
    nombre: 'MATRÍCULA DEL PED EN FINANZAS',
    descripcionCorta:
      'Domina las técnicas eficaces para gestionar los recursos financieros de tu empresa, tomando decisiones gerenciales acertadas en el área financiera. Realiza análisis financieros proponiendo diferentes soluciones.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 161,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos05_L8UkqB3DwFyLLHRc5Vw0_f16c3149-f2ff-4013-9ac4-453f9f0fcf48.jpg',
    nombre: 'PED EN GESTIÓN LOGÍSTICA',
    descripcionCorta:
      'Diseña, modifica y optimiza sistemas logísticos para empresas de setores productios y de servicios, tomando decisiones eficaces en relación a almacenes de cadena o suministros  inventarios. Incorpora a tus actividades laborales el alcance global y be',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 162,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos05_uea656teFMOLbLC21iOb_c3c166a6-97ed-4c27-8afb-3ed68063a110.jpg',
    nombre: 'MATRÍCULA DEL PED EN GESTIÓN LOGÍSTICA',
    descripcionCorta:
      'Diseña, modifica y optimiza sistemas logísticos para empresas de setores productios y de servicios, tomando decisiones eficaces en relación a almacenes e inventarios. Incorpora a tus actividades laborales el alcance global y beneficios de cadena de s',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 163,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos10_LFZFhB4PcI1jKAUF2XUj_8693c493-f48c-4ad4-ae5b-771b93d23674.jpg',
    nombre: 'PED EN LIDERAZGO Y HABILIDADES BLANDAS',
    descripcionCorta:
      'Para ser líderes hoy en día es indispensable adquirir ciertas habilidades que potencien tu desarrollo personal, social y laboral con el fin de llevar a tu equipo, o tu organización a niveles superiores. Las empresas, cada vez más buscan ',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 164,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos10_F90Ontrx1rONCkYCV9gE_dcfa6613-c40a-403f-9bc6-85de6ffa8a73.jpg',
    nombre: 'MATRÍCULA DEL PED EN LIDERAZGO Y HABILIDADES BLANDAS',
    descripcionCorta:
      'Para ser líderes hoy en día es indispensable adquirir ciertas habilidades que potencien tu desarrollo personal, social y laboral con el fin de llevar a tu equipo, o tu organización a niveles superiores. Las empresas, cada vez más buscan líderes que s',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 165,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos01_t7fDkUK3jhvZ26YS3ktb_61580462-9ce8-4659-a086-b206aae127a9.jpg',
    nombre: 'PED EN ADMINISTRACIÓN',
    descripcionCorta:
      'Aprende a manejar eficientemente cualquier tipo de negocio, adquiriendo capacidades para generar valor para tu empresa, gestionando el crecimiento y desarrollo de la misma.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 166,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos01_xwCfc6QulmdCnhx6c1tp_9b0dc0ea-264b-472f-a900-284f75e54424.jpg',
    nombre: 'MATRÍCULA DEL PED EN ADMINISTRACIÓN',
    descripcionCorta:
      'Aprende a manejar eficientemente cualquier tipo de negocio, adquiriendo capacidades para generar valor para tu empresa, gestionando el crecimiento y desarrollo de la misma.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 167,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos04_CO5VInux2hSM5gkUVZqP_f5464396-7ef2-4a2b-9e03-9363fe598db1.jpg',
    nombre: 'PED EN GESTIÓN DEL TALENTO HUMANO',
    descripcionCorta:
      'Obtén las competencias necesarias para analizar íntegramente las tendencias mundiales en gestión del personal y aplicarlas en tu empresa, impulsando el crecimiento y desarrollo del talento humano. Evalúa con precisión el desempeño laboral de los trab',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 168,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos04_qXqypA8n2l9U6XYGcaUB_f37f84c0-a5cc-4875-b348-a3466c7e9942.jpg',
    nombre: 'MATRÍCULA DEL PED EN GESTIÓN DEL TALENTO HUMANO',
    descripcionCorta:
      'Obtén las competencias necesarias para analizar íntegramente las tendencias mundiales en gestión del personal y aplicarlas en tu empresa, impulsando el crecimiento y desarrollo del talento humano. Evalúa con precisión el desempeño laboral de los trab',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 169,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos02_MOPR9HYRGkW9oPqawxa7_0edea641-3c88-4673-8905-d5d00ebd9c86.jpg',
    nombre: 'PED EN GESTIÓN COMERCIAL',
    descripcionCorta:
      'El crecimiento empresarial depende fundamentalmente de sus ventas y de la lealtad de los clientes, por lo que es imprescindible conocer el mercado y su comportamiento, así como desarrollar estrategias efectivas de marketing y comunicació',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 170,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos02_816JiqU3dEppbSgoc4ck_79df7c2e-cd0d-4864-bfec-4cd22d7e53ae.jpg',
    nombre: 'MATRÍCULA DEL PED EN GESTIÓN COMERCIAL',
    descripcionCorta:
      'El crecimiento empresarial depende fundamentalmente de sus ventas y de la lealtad de los clientes, por lo que es imprescindible conocer el mercado y su comportamiento, así como desarrollar estrategias efectivas de marketing y comunicación.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 171,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos06_oS5zoagmzFkd7DE3nUoi_6ac85b00-98c4-4fd6-aea4-b3154afe17cc.jpg',
    nombre: 'PED EN GESTIÓN TRIBUTARIA',
    descripcionCorta:
      'Aporta a la gestión formal y segura de tu organización, tomando decisiones acertadas en relación a las obligaciones  tributarias de tu empresa. Resuelve la problemática fiscal de las empresas y las personas.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 172,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos06_LZDVs7sEsYSHApb87AkB_3ee8579a-0be9-4209-ba33-6ec8db424315.jpg',
    nombre: 'MATRÍCULA DEL PED EN GESTIÓN TRIBUTARIA',
    descripcionCorta:
      'Aporta a la gestión formal y segura de tu organización, tomando decisiones acertadas en relación a las obligaciones  tributarias de tu empresa. Resuelve la problemática fiscal de las empresas y las personas.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 173,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2000.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos07_AywuNZZ13eGayoDSkqbv_15d32963-c2cc-4d35-9a32-731ac4850441.jpg',
    nombre: 'PED EN GESTIÓN DE PROYECTOS',
    descripcionCorta:
      'Trabaja en grandes equipos gestionando proyectos en base al PMBOK, gestionando las técnicas y herramientas de gestión de proyectos en base a las normas PMI.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 174,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 550.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos07_VDytzMoQSqrqApHQ8NLe_21bc6ced-b596-4703-887b-643ef21e4e8a.jpg',
    nombre: 'MATRÍCULA DEL PED EN GESTIÓN DE PROYECTOS',
    descripcionCorta:
      'Trabaja en grandes equipos gestionando proyectos en base al PMBOK, gestionando las técnicas y herramientas de gestión de proyectos en base a las normas PMI',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 175,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2500.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos08_4ImMa1FcEcjHI4Ujf90G_678bd476-8e04-4af2-96b4-3ac7dff2b7fb.jpg',
    nombre: 'PED EN MARKETING DIGITAL ',
    descripcionCorta:
      'Gestiona la presencia digital de la empresa en el mercado dominando las principales técnicas y herramientas del marketing digital, implementa campañas integrales de marketing flexibles , dinámicas y segmentadas.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 176,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 675.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos08_nX25YvxN705u8O30TmoB_e43ecf16-97c9-4633-a547-f6e5358ca738.jpg',
    nombre: 'MATRÍCULA DEL PED EN MARKETING DIGITAL ',
    descripcionCorta:
      'Gestiona la presencia digital de la empresa en el mercado dominando las principales técnicas y herramientas del marketing digital, implementa campañas integrales de marketing flexibles , dinámicas y segmentadas.',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 177,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2500.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos09_flc1e68UZOZ9HDp0sEq3_77e0c693-2d25-4b3e-aa0c-d85e8e4a1423.jpg',
    nombre: 'PED EN INNOVACIÓN Y EMPRENDIMIENTO',
    descripcionCorta:
      'Desarrollado por la Incubadora de Negocios Kaman de la Universidad Católica San Pablo brinda a los participantes, de manera muy práctica, los conocimientos y herramientas actuales apropiadas para desarrollar potentes competencias de inno',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 178,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 675.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagos09_WecBWS4e7iZjHHmhbkVy_000e0f31-4f35-4ba8-8451-e9500765a105.jpg',
    nombre: 'MATRÍCULA DEL PED EN INNOVACIÓN Y EMPRENDIMIENTO',
    descripcionCorta:
      'Desarrollado por la Incubadora de Negocios Kaman de la Universidad Católica San Pablo brinda a los participantes, de manera muy práctica, los conocimientos y herramientas actuales apropiadas para desarrollar potentes competencias de innovación centra',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1011,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 212,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 155.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/image_KaQDSh12NpvJxmdRwCJn_07c9d6ab-b12e-4eef-91cb-16f5365a1232.png',
    nombre: 'Curso de Orientación Vocacional y Profesional online',
    descripcionCorta: '¿Y ahora qué sigue?',
    descripcionExtendida: null,
    catDescripcion: 'CURSOS',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1014,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 219,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 65.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/SECRETOSEMPRESARIALESDELOSMONJESTRAPENSES_gCIrFIuWZXouM2eMhYCt_283dc4f2-5f22-4c3a-81e7-15b8f370addf.jpg',
    nombre: 'SECRETOS EMPRESARIALES DE LOS MONJES TRAPENSES',
    descripcionCorta: 'Responsabilidad Social de la Empresa',
    descripcionExtendida: null,
    catDescripcion: 'LIBRO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 2,
    idCatego: 1,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 221,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2100.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/UCSPFCYellowPasarellacono_4x9fELitgDGI71kB4hM3_225ab63b-50c1-4226-9ff4-294e40bcfc9b.jpg',
    nombre: 'LEAN SIX SIGMA - YELLOW BELT',
    descripcionCorta: 'Lean Six Sigma - Yellow Belt',
    descripcionExtendida: null,
    catDescripcion: 'CURSOS',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1014,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 222,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 710.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/UCSPFCLEPasarellaDigital_p7c8H3A9f6GOkaw0SxG8_59f93555-350f-4ae8-a13b-b6c5f5a7fec3.jpg',
    nombre: 'Programa de Liderazgo Estratégico y Trabajo en Equipo.',
    descripcionCorta:
      'Curso 100% online que brinda los conocimientos, experiencias y herramientas fundamentales para trabajar los aspectos personas que nos impiden ser mas eficaces en todos los ámbitos de nuestra vida, así como potenciar las habilidades sociales para apre',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1010,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 230,
    idProdCam: 33,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 300.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/TiendaOnlinepatologia1_v7hnDHtxZKylYJUis2vW_a9cb4432-347d-44ea-9ed1-be6b048ff4e3.jpg',
    nombre:
      'Diplomado en Patología y Rehabilitación de Estructuras de Concreto Reforzado',
    descripcionCorta:
      'Diplomado en Patología y Rehabilitación de Estructuras de Concreto Reforzado',
    descripcionExtendida: null,
    catDescripcion: 'DIPLOMADO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1005,
    idCatego: 6,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-12-07T19:00:00',
    metodoPago: 'Matrícula',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 232,
    idProdCam: 37,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 340.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosOPENCV_ZOQs1aZpHqkqConYYKdf_66def28c-03b1-4ad2-8814-ccc92822dac2.jpg',
    nombre: 'VISIÓN POR COMPUTADOR USANDO OPENCV',
    descripcionCorta: 'Visión por Computador Usando Opencv',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-07T17:00:00',
    metodoPago: 'Pronto Pago',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 233,
    idProdCam: 38,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 300.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/UCSPFC3DPasarellacono_7oYOcxnGlkzFtqIjzLVQ_4f1b00be-daa0-42e5-ad3e-e7cf110699dc.jpg',
    nombre: 'INTRODUCCIÓN AL DISEÑO E IMPRESIÓN 3D',
    descripcionCorta: 'Introducción al diseño e impresión 3D',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-13T19:30:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 234,
    idProdCam: 40,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/UCSPELCSistemaAficheMailing_36d5dGgnqhvK3LFgLiWo_121338fe-2b1c-472f-ae38-e3597435cd5b.jpg',
    nombre:
      'Certificado curso Fabricación Digital - Ing. Electrónica y de Telecomunicaciones',
    descripcionCorta:
      'Ing. Electrónica y de Telecomunicaciones - Certificado curso Fabricación Digital ',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-09-30T23:59:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 235,
    idProdCam: 41,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/UCSPELCSistemaAficheMailing_kw0SJLST5y50D5FDCSEl_c4fbc573-1fd4-4b57-b1d8-958a750254c0.jpg',
    nombre: 'Certificado curso Fabricación Digital - Ing. Mecatrónica',
    descripcionCorta:
      'Certificado curso Fabricación Digital - Ing. Mecatrónica',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-09-30T23:59:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 237,
    idProdCam: 43,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 150.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosPSICOLOGIAFORENSE_rrMMhTGuOGDDHOin5vU0_0aa717d7-aa3c-4253-9da8-100b26c754cf.jpg',
    nombre: 'NUEVAS TÉCNICAS EN PSICOLOGÍA FORENSE',
    descripcionCorta: 'Nuevas Técnicas en Psicología Forense',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-10T16:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 239,
    idProdCam: 45,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 150.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasareladepagos200x200GestindePlanillasCursoonlineFC1_azrtTSG4QmAhyjsXCyGs_05cff431-0254-48b0-b363-7f74ca1718a4.jpg',
    nombre: 'GESTIÓN DE PLANILLAS',
    descripcionCorta: 'Gestión de Planillas',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-26T18:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 240,
    idProdCam: 46,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 380.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosPAVIMENTACION_6Jr15tKtGDEl79cG4Bd5_d7cb29ee-1fe2-4002-9b1e-687136d5c555.jpg',
    nombre: 'CONSTRUCCION Y SUPERVISIÓN DE OBRAS DE PAVIMENTACION ASFÁLTICA',
    descripcionCorta:
      'Construccion y Supervisión de Obras de Pavimentacion Asfáltica',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-26T19:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 242,
    idProdCam: 48,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 165.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosDISEOMEZCLACONCRETO_aji0tCvuaDTmobcSo2ip_5f60c9f5-f991-4267-ad8d-1736fe7283c5.jpg',
    nombre: 'DISEÑO DE MEZCLA DEL CONCRETO',
    descripcionCorta: 'Diseño de Mezcla del Concreto',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-13T19:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 243,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 2400.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosDERECHOADMINISTRATIVOCONTRATACIONES_lntW1GxJ54iCkyKEoKQz_c304037b-6499-45bb-aab1-5d22730b1d27.jpg',
    nombre:
      'DERECHO ADMINISTRATIVO, CONTRATACIONES CON EL ESTADO Y ARBITRAJE EN CONTRATACIÓN ESTATAL',
    descripcionCorta:
      'Derecho Administrativo, Contrataciones con el Estado y Arbitraje en Contratación Estatal',
    descripcionExtendida: null,
    catDescripcion: 'PROGRAMA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1005,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 245,
    idProdCam: 50,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 150.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosSTAKEHOLDERS_OknK9UkqHLpsvQUiB9M1_99446326-bbca-4df6-b680-968f68eaa916.jpg',
    nombre: 'REPUTACIÓN Y TRABAJO CON STAKEHOLDERS ',
    descripcionCorta: 'Reputación y trabajo con stakeholders ',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-20T19:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 246,
    idProdCam: 51,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 180.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosNUEVANORMALIDADTRABAJO_JXKD793SgEn6mjTEK0yM_7c038306-5e1d-4644-afe1-02e35d5431f4.jpg',
    nombre: 'NUEVA NORMALIDAD EN LAS RELACIONES DE TRABAJO',
    descripcionCorta: 'Nueva Normalidad en las Relaciones de Trabajo',
    descripcionExtendida: null,
    catDescripcion: 'CURSO',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 5,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-16T17:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 250,
    idProdCam: 55,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AficheJornadasdeTecnologaDIEEpyKE1xX3WwGDrOtQUmWq0cd2fa776e3d403cbae6a85c513f89b7_cnWcPDRzjYfLuRgOixi1_a513377c-162a-4109-a5c0-e3cd9f650f21.jpg',
    nombre: 'Certificado curso Fabricación Digital - Ing. Mecatrónica',
    descripcionCorta:
      'Certificado curso Fabricación Digital - Ing. Mecatrónica',
    descripcionExtendida: null,
    catDescripcion: 'JORNADA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1019,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-31T23:59:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 251,
    idProdCam: 56,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AficheJornadasdeTecnologaDIEEpyKE1xX3WwGDrOtQUmWq0cd2fa776e3d403cbae6a85c513f89b7_XrJiiWBEMPNwkbMpPwSE_7c93d007-fa84-4b2c-a162-4f1c1dff96ec.jpg',
    nombre:
      'Certificado Jornadas de Tecnología en Ingeniería Electrónica y Telecomunicaciones',
    descripcionCorta:
      'Alumnos de Ingeniería Electrónica y de Telecomunicaciones',
    descripcionExtendida: null,
    catDescripcion: 'JORNADA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1019,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-31T00:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 254,
    idProdCam: 59,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 10.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/AficheJornadasdeTecnologaDIEEpyKE1xX3WwGDrOtQUmWq0cd2fa776e3d403cbae6a85c513f89b7_W9qZnfLPZo2DeUgIqsDi_c8cef9f8-ac12-4df7-8ea1-07a49f105962.jpg',
    nombre: 'Certificado Jornadas de Tecnología en Mecatrónica.',
    descripcionCorta: 'Alumnos de Ingeniería Mecatrónica',
    descripcionExtendida: null,
    catDescripcion: 'JORNADA',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1019,
    nombreTienda: 'Todos',
    fechaInicioCurso: '2020-10-31T00:00:00',
    metodoPago: 'Pago Total',
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
  {
    idProduct: 255,
    idProdCam: 0,
    itemTarifario: 0,
    precioRebajado: 0.0,
    precioNormal: 180.0,
    filePortada:
      'https://ied.blob.core.windows.net/academico/ventadigital/files/pasarelapagosPHYTON_mGpvzlIV3fY86hPqjOEA_20e52bcd-a50a-4ceb-961b-7d8caad2711b.jpg',
    nombre: 'PYTHON PARA APLICACIONES EN CIENCIA E INGENIERÍA',
    descripcionCorta: 'Python para Aplicaciones en Ciencia e Ingeniería',
    descripcionExtendida: null,
    catDescripcion: 'CURSOS',
    peso: 0.0,
    dimensiones: null,
    valoraciones: false,
    tiendaIdTienda: 1004,
    idCatego: 1014,
    nombreTienda: 'Todos',
    fechaInicioCurso: null,
    metodoPago: null,
    productosVinculados: null,
    academico: null,
    grupo: null,
    curso: null,
  },
];

export { products };
